apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert.k8s.yaml
  - service.k8s.yaml
  - deployment.k8s.yaml
# manual deployment only
# ci pipeline does not have git/gitattributes filter
# to decode the encrypted file
# patchesStrategicMerge:
#   - add_initstate.k8s.yaml
secretGenerator:
  - name: iglog-initstate
    files:
      - config/iglog.json
images:
  - name: us.gcr.io/com-seankhliao/iglog
    # newTag: IMAGE_TAG
