apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: iglog
  name: iglog
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: iglog
  ports:
    - port: 443
      targetPort: 8080
